const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function insertLivros() {
try{
await prisma.autores.createMany({
    data: [
        { nome: 'Emily Bronte', dataNascimento: new Date('1818-07-30'), nacionalidade: 'Reino Unido' },
        { nome: 'Hwang Bo-Reum', dataNascimento: new Date('1985-01-01'), nacionalidade: 'Coreia do Sul' },
        { nome: 'Franz Kafka', dataNascimento: new Date('1883-07-03'), nacionalidade: 'Áustria-Hungria' },
        { nome: 'Harper Lee', dataNascimento: new Date('1926-04-28'), nacionalidade: 'Estados Unidos' },
        { nome: 'Lima Barreto', dataNascimento: new Date('1881-05-13'), nacionalidade: 'Brasil' },
        { nome: 'C. J. Tudor', dataNascimento: new Date('1972-01-01'), nacionalidade: 'Reino Unido' },
        { nome: 'Holly Jackson', dataNascimento: new Date('1992-01-01'), nacionalidade: 'Reino Unido' },
        { nome: 'Socorro Acioli', dataNascimento: new Date('1975-02-28'), nacionalidade: 'Brasil' },
        { nome: 'Aline Bei', dataNascimento: new Date('1987-01-01'), nacionalidade: 'Brasil' },
        { nome: 'Gabriel García Márquez', dataNascimento: new Date('1927-03-06'), nacionalidade: 'Colômbia' },
        { nome: 'Sally Rooney', dataNascimento: new Date('1991-02-20'), nacionalidade: 'Irlanda' },
        { nome: 'Taylor Jenkins Reid', dataNascimento: new Date('1983-12-20'), nacionalidade: 'Estados Unidos' },
        { nome: 'Valérie Perrin', dataNascimento: new Date('1967-01-01'), nacionalidade: 'França' },
        { nome: 'Ayòbámi Adébáyò', dataNascimento: new Date('1988-01-01'), nacionalidade: 'Nigéria' },
        { nome: 'Coco Mellors', dataNascimento: new Date('1990-01-01'), nacionalidade: 'Reino Unido' },
        { nome: 'Alba de Céspedes', dataNascimento: new Date('1911-03-11'), nacionalidade: 'Itália' },
        { nome: 'Hannah Nicole Maehrer', dataNascimento: new Date('1995-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Raphael Montes', dataNascimento: new Date('1990-09-22'), nacionalidade: 'Brasil' },
        { nome: 'Rebecca Yarros', dataNascimento: new Date('1980-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Riley Sager', dataNascimento: new Date('1974-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Leslie Wolfe', dataNascimento: new Date('1970-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Freida McFadden', dataNascimento: new Date('1978-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Christina Lauren', dataNascimento: new Date('1980-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Lauren Roberts', dataNascimento: new Date('1996-01-01'), nacionalidade: 'Reino Unido' },
        { nome: 'Felipe Rocha', dataNascimento: new Date('1990-01-01'), nacionalidade: 'Brasil' },
        { nome: 'Karen M. McManus', dataNascimento: new Date('1969-01-01'), nacionalidade: 'Estados Unidos' },
        { nome: 'Carley Fortune', dataNascimento: new Date('1984-01-01'), nacionalidade: 'Canadá' },
        { nome: 'Igor Pires', dataNascimento: new Date('1993-01-01'), nacionalidade: 'Brasil' },
        { nome: 'Erin Doom', dataNascimento: new Date('1995-01-01'), nacionalidade: 'Itália' },
  ]
});
    
const livros = [
    {
      "titulo": "Todas as suas (im)perfeições",
      "ano": 2019,
      "edicao": "23ª",
      "isbn": "8501117684",
      "precoCusto": 30.00,
      "precoVenda": 41.90,
      "dataPublicacao": "2019-07-24T00:00:00Z",
      "paginas": 304,
      "sinopse": "Todas as suas imperfeições narra a história de Quinn e Graham. Eles se conhecem no pior dia de suas vidas; ela chega mais cedo de uma viagem para surpreender o noivo, ele testemunha a traição da namorada. E é assim que ambos acabam no corredor de um prédio, trocando confidências, biscoitos da sorte e palavras de conforto. \nFim da dança... se o destino não tivesse outros planos para os dois. Meses mais tarde, os acordes tocam para o casal mais uma vez e eles se reencontram. Graham está convencido de que são almas gêmeas. Quinn jamais se sentiu dessa forma antes. A intensidade do sentimento os assusta, mas eles mergulham de cabeça mesmo assim.",
      "status": "disponível",
      "altura": 20.57,
      "largura": 13.46,
      "peso": 0.32,
      "profundidade": 2.03,
      "codigoBarras": "8501117684",
      "autorId": 2,
      "editoraId": 1,
      "fornecedorId": 1,
      "grupoPrecificacaoId": 1,
      "categoriaId": 1,
      "estoqueId": 1
    },
    {
        "titulo": 'Até o verão terminar',
        "ano": 2021,
        "edicao": '21ª',
        "isbn": '6559810372',
        "precoCusto": 32.00,
        "precoVenda": 41.90,
        "dataPublicacao": '2021-08-30T00:00:00Z',
        "paginas": 336,
        "sinopse": 'Filha de uma mãe problemática e um pai ausente... (texto completo conforme fornecido)',
        "status": 'disponível',
        "altura": 121.0,
        "largura": 13.5,
        "peso": 0.8,
        "profundidade": 1.9,
        "codigoBarras": '6559810372',
        "autorId": 9,
        "editoraId": 2,
        "fornecedorId": 2,
        "grupoPrecificacaoId": 2,
        "categoriaId": 2,
        "estoqueId": 2
    },
    {
        "titulo": "O morro dos ventos uivantes",
        "ano": 2020,
        "edicao": "1ª",
        "isbn": "9786586016258",
        "precoCusto": 30.00,
        "precoVenda": 41.90,
        "dataPublicacao": "2020-01-01T00:00:00Z",
        "paginas": 376,
        "sinopse": "Publicado originalmente em 1847 sob o pseudônimo de Ellis Bell, O Morro dos Ventos Uivantes é o único romance da escritora britânica Emily Brontë. Considerado um clássico da literatura inglesa, a obra narra a trágica e tempestuosa história de amor entre Heathcliff e Catherine Earnshaw, ambientada nos campos isolados de Yorkshire.",
        "status": "disponível",
        "altura": 23.00,
        "largura": 16.00,
        "peso": 0.45,
        "profundidade": 3.00,
        "codigoBarras": "9786586016258",
        "autorId": 9,
        "editoraId": 1,
        "fornecedorId": 1,
        "grupoPrecificacaoId": 1,
        "categoriaId": 1,
        "estoqueId": 1
    },
    {
        "titulo": "Bem-vindos à livraria Hyunam-dong",
        "ano": 2023,
        "edicao": "1ª",
        "isbn": "9786555655820",
        "precoCusto": 34.00,
        "precoVenda": 49.90,
        "dataPublicacao": "2023-04-17T00:00:00Z",
        "paginas": 336,
        "sinopse": "Quando Yeongju, uma mulher comum cansada da rotina corporativa, decide abrir uma pequena livraria em um bairro tranquilo de Seul, ela não imagina que vai encontrar em meio aos livros uma nova forma de enxergar a vida. Entre clientes, novos amigos e desafios, a livraria Hyunam-dong se torna um refúgio para almas que buscam reconexão.",
        "status": "disponível",
        "altura": 23.00,
        "largura": 15.50,
        "peso": 0.40,
        "profundidade": 2.30,
        "codigoBarras": "9786555655820",
        "autorId": 10,
        "editoraId": 1,
        "fornecedorId": 1,
        "grupoPrecificacaoId": 1,
        "categoriaId": 1,
        "estoqueId": 1
    },
    {
        "titulo": "A Metamorfose",
        "ano": 1915,
        "edicao": "1ª",
        "isbn": "9788535912872",
        "precoCusto": 18.00,
        "precoVenda": 29.90,
        "dataPublicacao": "1915-01-01T00:00:00Z",
        "paginas": 128,
        "sinopse": "Em 'A Metamorfose', Franz Kafka narra a história de Gregor Samsa, um homem comum que, ao acordar, se vê transformado em um inseto gigante. A obra trata da alienação, da perda de identidade e da solidão, enquanto Gregor tenta lidar com a estranha situação e com a reação de sua família diante da sua metamorfose. A história é um mergulho existencial e psicológico, questionando a natureza humana e as relações familiares.",
        "status": "disponível",
        "altura": 20.00,
        "largura": 13.00,
        "peso": 0.18,
        "profundidade": 1.50,
        "codigoBarras": "9788535912872",
        "autorId": 11,
        "editoraId": 1,
        "fornecedorId": 1,
        "grupoPrecificacaoId": 1,
        "categoriaId": 2,
        "estoqueId": 1
        },
        {
  "titulo": "O Sol é para Todos",
  "ano": 1960,
  "edicao": "1ª",
  "isbn": "9788535910137",
  "precoCusto": 35.00,
  "precoVenda": 49.90,
  "dataPublicacao": "1960-07-11T00:00:00Z",
  "paginas": 336,
  "sinopse": "O Sol é para Todos é uma das obras mais importantes da literatura americana. Situada na década de 1930, na cidade fictícia de Maycomb, o romance de Harper Lee narra a história de Scout Finch, uma menina que, junto com seu irmão Jem e seu pai, Atticus Finch, enfrenta a tensão racial e os dilemas morais da época. Quando Atticus, advogado respeitado, defende um homem negro injustamente acusado de estupro, a história revela as profundas divisões sociais e raciais do sul dos Estados Unidos.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.38,
  "profundidade": 2.50,
  "codigoBarras": "9788535910137",
  "autorId": 12,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 3,
  "estoqueId": 1
},
{
  "titulo": "Os Bruzundangas",
  "ano": 1923,
  "edicao": "1ª",
  "isbn": "9788520912681",
  "precoCusto": 25.00,
  "precoVenda": 39.90,
  "dataPublicacao": "1923-01-01T00:00:00Z",
  "paginas": 192,
  "sinopse": "Em 'Os Bruzundangas', Lima Barreto faz uma crítica satírica à sociedade brasileira do início do século XX. O livro é uma farsa política e social, onde Barreto imagina um país fictício, os Bruzundangas, com uma sociedade marcada por absurdos e corrupções. A obra traz uma reflexão sobre o atraso, a ignorância e a hipocrisia das instituições e dos costumes da época, utilizando o humor e o sarcasmo para expor suas críticas.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.30,
  "profundidade": 1.80,
  "codigoBarras": "9788520912681",
  "autorId": 13,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 4,
  "estoqueId": 1
},
    {
  "titulo": "O Homem de Giz",
  "ano": 2018,
  "edicao": "1ª",
  "isbn": "9788551006461",
  "precoCusto": 40.00,
  "precoVenda": 59.90,
  "dataPublicacao": "2018-01-01T00:00:00Z",
  "paginas": 320,
  "sinopse": "'O Homem de Giz' é um thriller psicológico de C. J. Tudor que mistura mistério e tensão. A história segue Eddie, que, ao relembrar os eventos de sua infância, se vê imerso em uma série de mortes e segredos envolvendo um homem misterioso com um estranho símbolo desenhado com giz. Ambientado em uma cidadezinha, o livro explora amizade, traumas do passado e a luta entre o bem e o mal, com reviravoltas surpreendentes até o final.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.40,
  "profundidade": 2.00,
  "codigoBarras": "9788551006461",
  "autorId": 14,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 5,
  "estoqueId": 1
},
{
  "titulo": "Manual de Assassinato para Boas Garotas",
  "ano": 2020,
  "edicao": "1ª",
  "isbn": "9786555611092",
  "precoCusto": 42.00,
  "precoVenda": 69.90,
  "dataPublicacao": "2020-10-14T00:00:00Z",
  "paginas": 416,
  "sinopse": "'Manual de Assassinato para Boas Garotas' de Holly Jackson é um thriller psicológico que segue a história de Pippa Fitz-Amobi, uma estudante do ensino médio que decide investigar um caso de assassinato não resolvido de seu bairro. Durante sua pesquisa, ela começa a desenterrar segredos sombrios sobre o que realmente aconteceu, levando a um mistério mais profundo e perigoso do que ela imaginava. A obra mistura mistério, suspense e uma narrativa cheia de reviravoltas inesperadas.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.44,
  "profundidade": 3.00,
  "codigoBarras": "9786555611092",
  "autorId": 15,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 5,
  "estoqueId": 1
},
{
  "titulo": "A Cabeça do Santo",
  "ano": 2016,
  "edicao": "1ª",
  "isbn": "9788535912681",
  "precoCusto": 28.00,
  "precoVenda": 44.90,
  "dataPublicacao": "2016-01-01T00:00:00Z",
  "paginas": 304,
  "sinopse": "'A Cabeça do Santo' é um romance de Socorro Acioli que mistura o real e o fantástico para contar a história de dois jovens que vivem em um pequeno vilarejo do sertão nordestino. A trama envolve uma cabeça de santo que, segundo a lenda, possui poderes milagrosos, além de elementos de fé, misticismo e a luta dos personagens por um futuro melhor. O livro aborda temas como identidade, religiosidade e o valor da tradição popular.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.35,
  "profundidade": 2.20,
  "codigoBarras": "9788535912681",
  "autorId": 16,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 6,
  "estoqueId": 1
},
{
  "titulo": "Pequena Coreografia do Adeus",
  "ano": 2017,
  "edicao": "1ª",
  "isbn": "9788535917891",
  "precoCusto": 30.00,
  "precoVenda": 49.90,
  "dataPublicacao": "2017-03-28T00:00:00Z",
  "paginas": 224,
  "sinopse": "'Pequena Coreografia do Adeus' é o romance de estreia de Aline Bei, que narra a história de uma jovem mulher em busca de sua identidade e da reconstrução de sua vida após a perda e o abandono. A trama aborda o luto, o amor e o processo de amadurecimento emocional. Com uma escrita delicada e poética, o livro é uma reflexão sobre os sentimentos humanos e a busca por um sentido após as perdas que a vida nos impõe.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.30,
  "profundidade": 1.80,
  "codigoBarras": "9788535917891",
  "autorId": 17,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 7,
  "estoqueId": 1
},
{
  "titulo": "Em Agosto Nos Vemos",
  "ano": 1999,
  "edicao": "1ª",
  "isbn": "9788535915279",
  "precoCusto": 35.00,
  "precoVenda": 54.90,
  "dataPublicacao": "1999-01-01T00:00:00Z",
  "paginas": 160,
  "sinopse": "'Em Agosto Nos Vemos' é uma obra de Gabriel García Márquez que mistura realismo mágico e introspecção. A história segue a vida de um homem que, após a morte de sua esposa, tenta lidar com a perda e o vazio deixado por ela. O livro é uma reflexão sobre a morte, o amor e o tempo, com uma narrativa que mistura o fantástico com o cotidiano, característica marcante da obra de Márquez.",
  "status": "disponível",
  "altura": 20.00,
  "largura": 13.00,
  "peso": 0.30,
  "profundidade": 1.60,
  "codigoBarras": "9788535915279",
  "autorId": 18,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 8,
  "estoqueId": 1
},
{
  "titulo": "Pessoas Normais",
  "ano": 2018,
  "edicao": "1ª",
  "isbn": "9788535917235",
  "precoCusto": 38.00,
  "precoVenda": 59.90,
  "dataPublicacao": "2018-08-27T00:00:00Z",
  "paginas": 368,
  "sinopse": "'Pessoas Normais' é o romance de estreia de Sally Rooney que explora as complexas relações entre dois jovens, Connell e Marianne, enquanto eles enfrentam questões de identidade, amor, classe social e amizade. A história se passa na Irlanda e acompanha esses dois personagens desde o ensino médio até a vida adulta, com uma escrita que mistura uma análise profunda das emoções humanas e as nuances da vida cotidiana.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.40,
  "profundidade": 2.50,
  "codigoBarras": "9788535917235",
  "autorId": 19,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 9,
  "estoqueId": 1
},
{
  "titulo": "Amor(es) Verdadeir(os)",
  "ano": 2021,
  "edicao": "1ª",
  "isbn": "9786584560353",
  "precoCusto": 40.00,
  "precoVenda": 59.90,
  "dataPublicacao": "2021-02-22T00:00:00Z",
  "paginas": 368,
  "sinopse": "'Amor(es) Verdadeir(os)' é uma história de Taylor Jenkins Reid que explora as complexas relações amorosas entre os personagens, com um foco nas diferentes formas de amar e as escolhas que moldam a vida de cada um. O livro mistura questões de identidade, traição e redescoberta do próprio eu, levando os leitores a refletirem sobre o que é o verdadeiro amor e até onde estamos dispostos a ir por ele.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.38,
  "profundidade": 2.50,
  "codigoBarras": "9786584560353",
  "autorId": 20,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 10,
  "estoqueId": 1
},
{
  "titulo": "Três",
  "ano": 2020,
  "edicao": "1ª",
  "isbn": "9786555613249",
  "precoCusto": 48.00,
  "precoVenda": 74.90,
  "dataPublicacao": "2020-09-18T00:00:00Z",
  "paginas": 448,
  "sinopse": "'Três' é um romance de Valérie Perrin que segue a história de três personagens unidos pelo passado e pelos segredos que compartilham. O livro explora os temas da amizade, do perdão e da complexidade das relações humanas, com uma narrativa que mergulha na psicologia dos personagens, refletindo sobre como as escolhas e os erros do passado moldam o presente. É uma história cheia de emoção, reviravoltas e reflexão.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.44,
  "profundidade": 2.90,
  "codigoBarras": "9786555613249",
  "autorId": 21,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 11,
  "estoqueId": 1
},
{
  "titulo": "Fique Comigo",
  "ano": 2017,
  "edicao": "1ª",
  "isbn": "9788551005242",
  "precoCusto": 39.00,
  "precoVenda": 59.90,
  "dataPublicacao": "2017-11-01T00:00:00Z",
  "paginas": 336,
  "sinopse": "'Fique Comigo' de Ayòbámi Adébáyò é uma poderosa história de amor e tragédia ambientada na Nigéria. A trama gira em torno de Yejide e Akin, um casal que enfrenta dificuldades no casamento devido à pressão familiar e questões de infertilidade. O romance é uma reflexão sobre as expectativas culturais, as relações familiares e o que acontece quando as tradições e os sentimentos entram em conflito. A escrita delicada e envolvente faz do livro uma obra inesquecível.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.42,
  "profundidade": 2.50,
  "codigoBarras": "9788551005242",
  "autorId": 22,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 12,
  "estoqueId": 1
},
{
  "titulo": "Cleopatra e Frankenstein",
  "ano": 2021,
  "edicao": "1ª",
  "isbn": "9786555616875",
  "precoCusto": 50.00,
  "precoVenda": 79.90,
  "dataPublicacao": "2021-06-08T00:00:00Z",
  "paginas": 352,
  "sinopse": "'Cleopatra e Frankenstein' é o romance de estreia de Coco Mellors, que conta a história de uma jovem chamada Cleopatra, que se apaixona por um homem mais velho, o carismático Frank. O livro explora a complexidade das relações, especialmente em um relacionamento que parece ter tudo para dar certo, mas que enfrenta desafios profundos. O romance mistura amor, identidade e os dilemas de um casal, enquanto aborda temas de autodescoberta e desafios da vida adulta.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.42,
  "profundidade": 2.60,
  "codigoBarras": "9786555616875",
  "autorId": 23,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 13,
  "estoqueId": 1
},
{
  "titulo": "Caderno Proibido",
  "ano": 1950,
  "edicao": "1ª",
  "isbn": "9788520915828",
  "precoCusto": 35.00,
  "precoVenda": 54.90,
  "dataPublicacao": "1950-01-01T00:00:00Z",
  "paginas": 240,
  "sinopse": "'Caderno Proibido' é uma obra de Alba de Céspedes que narra a história de uma mulher que, ao iniciar a escrita de seu diário secreto, vai se deparando com a revelação de seus próprios sentimentos e emoções. O livro aborda temas como o feminismo, a repressão emocional e a descoberta de si mesma, enquanto a personagem tenta se entender e encontrar seu lugar em uma sociedade que impõe limites às mulheres.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.30,
  "profundidade": 1.80,
  "codigoBarras": "9788520915828",
  "autorId": 24,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 14,
  "estoqueId": 1
},
{
  "titulo": "Aprendiz do Vilão",
  "ano": 2021,
  "edicao": "1ª",
  "isbn": "9786584571595",
  "precoCusto": 30.00,
  "precoVenda": 49.90,
  "dataPublicacao": "2021-10-25T00:00:00Z",
  "paginas": 352,
  "sinopse": "'Aprendiz do Vilão' de Hannah Nicole Maehrer é um romance de fantasia que segue a trajetória de um jovem aprendiz que decide se tornar vilão. O livro explora temas como poder, escolha, e a linha tênue entre o bem e o mal, enquanto o protagonista se vê confrontado com os dilemas de seu destino e com as consequências de suas decisões. Uma narrativa cheia de aventura, com personagens complexos e reviravoltas inesperadas.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.38,
  "profundidade": 2.50,
  "codigoBarras": "9786584571595",
  "autorId": 25,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 15,
  "estoqueId": 1
},
{
  "titulo": "Uma Família Feliz",
  "ano": 2018,
  "edicao": "1ª",
  "isbn": "9788551005532",
  "precoCusto": 40.00,
  "precoVenda": 59.90,
  "dataPublicacao": "2018-06-04T00:00:00Z",
  "paginas": 352,
  "sinopse": "'Uma Família Feliz' é um thriller psicológico de Raphael Montes que traz uma trama envolvente e cheia de suspense. A história acompanha uma família aparentemente perfeita, mas que guarda segredos obscuros. O autor explora as complexidades das relações familiares, a violência e os mistérios que se escondem por trás de uma fachada de felicidade. Com uma narrativa tensa e personagens profundos, o livro é uma reflexão sobre o que é ser realmente feliz e até onde as pessoas vão para manter essa aparência.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.42,
  "profundidade": 2.60,
  "codigoBarras": "9788551005532",
  "autorId": 26,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 16,
  "estoqueId": 1
},
{
"titulo": "Quarta asa",
"ano": 2023,
"edicao": "1ª",
"isbn": "9786555655647",
"precoCusto": 38.00,
"precoVenda": 52.90,
"dataPublicacao": "2023-05-02T00:00:00Z",
"paginas": 560,
"sinopse": "Em Quarta asa, Violet Sorrengail está determinada a se tornar parte do prestigioso Quadrante de Dragões da Academia de Guerra de Basgiath, onde apenas os mais fortes sobrevivem. Cercada de conspirações, intrigas e batalhas, ela precisa lutar para conquistar seu dragão e sobreviver a cada desafio mortal.",
"status": "disponível",
"altura": 23.00,
"largura": 16.00,
"peso": 0.70,
"profundidade": 4.00,
"codigoBarras": "9786555655647",
"autorId": 27,
"editoraId": 1,
"fornecedorId": 1,
"grupoPrecificacaoId": 1,
"categoriaId": 1,
"estoqueId": 1
},
{
"titulo": "O massacre da família Hope",
"ano": 2023,
"edicao": "1ª",
"isbn": "9786555655944",
"precoCusto": 35.00,
"precoVenda": 49.90,
"dataPublicacao": "2023-06-20T00:00:00Z",
"paginas": 384,
"sinopse": "Quase três décadas após o brutal assassinato de sua família, Lenora Hope vive isolada em sua mansão, até contratar uma enfermeira que começa a investigar o que realmente aconteceu naquela noite sangrenta. Entre segredos, memórias distorcidas e verdades ocultas, a história do massacre da família Hope ganha novos contornos.",
"status": "disponível",
"altura": 23.00,
"largura": 16.00,
"peso": 0.58,
"profundidade": 2.70,
"codigoBarras": "9786555655944",
"autorId": 28,
"editoraId": 1,
"fornecedorId": 1,
"grupoPrecificacaoId": 1,
"categoriaId": 1,
"estoqueId": 1
},
{
"titulo": "Os sete maridos de Evelyn Hugo",
"ano": 2019,
"edicao": "1ª",
"isbn": "9788584391509",
"precoCusto": 30.00,
"precoVenda": 44.90,
"dataPublicacao": "2019-05-21T00:00:00Z",
"paginas": 360,
"sinopse": "Evelyn Hugo, lendária estrela de Hollywood, decide contar toda a verdade sobre sua vida glamourosa e controversa para uma jornalista iniciante. Entre segredos, escândalos e amores proibidos, Evelyn revela sua trajetória repleta de ambição, sacrifícios e seus sete casamentos marcantes.",
"status": "disponível",
"altura": 23.00,
"largura": 16.00,
"peso": 0.50,
"profundidade": 2.50,
"codigoBarras": "9788584391509",
"autorId": 29,
"editoraId": 1,
"fornecedorId": 1,
"grupoPrecificacaoId": 1,
"categoriaId": 1,
"estoqueId": 1
},
{
  "titulo": "A cirurgiã",
  "ano": 2017,
  "edicao": "1ª",
  "isbn": "9788501108107",
  "precoCusto": 28.00,
  "precoVenda": 39.90,
  "dataPublicacao": "2017-09-05T00:00:00Z",
  "paginas": 352,
  "sinopse": "Uma médica cirurgiã dedicada, Elizabeth Kane enfrenta uma série de assassinatos brutais ligados aos seus pacientes. Enquanto tenta desvendar a verdade, ela precisa lidar com suas próprias inseguranças e o perigo crescente que a cerca.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.38,
  "profundidade": 2.20,
  "codigoBarras": "9788501108107",
  "autorId": 30,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 1,
  "estoqueId": 1
},
{
  "titulo": "A empregada",
  "ano": 2021,
  "edicao": "1ª",
  "isbn": "9788594542587",
  "precoCusto": 29.00,
  "precoVenda": 42.90,
  "dataPublicacao": "2021-06-15T00:00:00Z",
  "paginas": 320,
  "sinopse": "Um suspense psicológico envolvente sobre uma jovem que aceita um emprego como empregada doméstica em uma casa aparentemente perfeita, mas logo descobre que nada ali é o que parece.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.37,
  "profundidade": 2.10,
  "codigoBarras": "9788594542587",
  "autorId": 31,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 1,
  "estoqueId": 1
},
{
  "titulo": "Imperfeitos",
  "ano": 2020,
  "edicao": "1ª",
  "isbn": "9788595081234",
  "precoCusto": 27.00,
  "precoVenda": 39.90,
  "dataPublicacao": "2020-09-10T00:00:00Z",
  "paginas": 288,
  "sinopse": "Uma comédia romântica que explora as imperfeições e desafios de um relacionamento improvável entre duas pessoas muito diferentes, mas que se completam.",
  "status": "disponível",
  "altura": 20.50,
  "largura": 13.50,
  "peso": 0.33,
  "profundidade": 2.00,
  "codigoBarras": "9788595081234",
  "autorId": 32,
  "editoraId": 1,
  "fornecedorId": 1,
  "grupoPrecificacaoId": 1,
  "categoriaId": 1,
  "estoqueId": 1
},
{
  "titulo": "Powerless",
  "ano": 2022,
  "edicao": "1ª",
  "isbn": "9788542205678",
  "precoCusto": 31.00,
  "precoVenda": 44.90,
  "dataPublicacao": "2022-03-18T00:00:00Z",
  "paginas": 352,
  "sinopse": "Em um mundo onde algumas pessoas nascem com superpoderes, uma jovem sem poderes luta para sobreviver e descobrir seu verdadeiro potencial.",
  "status": "disponível",
  "altura": 21.50,
  "largura": 14.00,
  "peso": 0.40,
  "profundidade": 2.30,
  "codigoBarras": "9788542205678",
  "autorId": 33,
  "editoraId": 4,
  "fornecedorId": 4,
  "grupoPrecificacaoId": 4,
  "categoriaId": 4,
  "estoqueId": 6
},
{
  "titulo": "Nem todo amor tem um final feliz. E tá tudo bem.",
  "ano": 2023,
  "edicao": "1ª",
  "isbn": "9786555654321",
  "precoCusto": 28.00,
  "precoVenda": 39.90,
  "dataPublicacao": "2023-01-10T00:00:00Z",
  "paginas": 288,
  "sinopse": "Um livro que aborda a aceitação dos términos amorosos, mostrando que nem todo amor precisa de um final feliz para ser válido.",
  "status": "disponível",
  "altura": 20.00,
  "largura": 13.00,
  "peso": 0.35,
  "profundidade": 2.10,
  "codigoBarras": "9786555654321",
  "autorId": 34,
  "editoraId": 3,
  "fornecedorId": 3,
  "grupoPrecificacaoId": 3,
  "categoriaId": 3,
  "estoqueId": 9
},
{
  "titulo": "Um de nós está mentindo",
  "ano": 2017,
  "edicao": "1ª",
  "isbn": "9788581637856",
  "precoCusto": 29.00,
  "precoVenda": 42.90,
  "dataPublicacao": "2017-07-04T00:00:00Z",
  "paginas": 336,
  "sinopse": "Cinco estudantes entram para a detenção, mas apenas quatro saem vivos. O mistério começa quando descobrem que um deles está mentindo.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.38,
  "profundidade": 2.25,
  "codigoBarras": "9788581637856",
  "autorId": 35,
  "editoraId": 2,
  "fornecedorId": 2,
  "grupoPrecificacaoId": 2,
  "categoriaId": 2,
  "estoqueId": 9
},
{
  "titulo": "Depois daquele verão",
  "ano": 2020,
  "edicao": "1ª",
  "isbn": "9788551004633",
  "precoCusto": 27.00,
  "precoVenda": 39.90,
  "dataPublicacao": "2020-12-01T00:00:00Z",
  "paginas": 304,
  "sinopse": "Quatro amigas lidam com os desafios do fim do verão e os segredos que ameaçam destruir suas vidas e amizades.",
  "status": "disponível",
  "altura": 20.50,
  "largura": 13.50,
  "peso": 0.34,
  "profundidade": 2.05,
  "codigoBarras": "9788551004633",
  "autorId": 36,
  "editoraId": 2,
  "fornecedorId": 2,
  "grupoPrecificacaoId": 2,
  "categoriaId": 3,
  "estoqueId": 7
},
{
  "titulo": "Textos cruéis demais para serem lidos rapidamente",
  "ano": 2021,
  "edicao": "1ª",
  "isbn": "9788542212010",
  "precoCusto": 28.00,
  "precoVenda": 41.90,
  "dataPublicacao": "2021-07-15T00:00:00Z",
  "paginas": 288,
  "sinopse": "Uma coletânea de textos curtos que exploram sentimentos profundos, reflexões sobre a vida e a complexidade das emoções humanas.",
  "status": "disponível",
  "altura": 20.00,
  "largura": 13.00,
  "peso": 0.30,
  "profundidade": 1.80,
  "codigoBarras": "9788542212010",
  "autorId": 37,
  "editoraId": 3,
  "fornecedorId": 3,
  "grupoPrecificacaoId": 3,
  "categoriaId": 4,
  "estoqueId": 3
},
{
  "titulo": "O fabricante de lágrimas",
  "ano": 2022,
  "edicao": "1ª",
  "isbn": "9786555656783",
  "precoCusto": 29.00,
  "precoVenda": 43.90,
  "dataPublicacao": "2022-05-20T00:00:00Z",
  "paginas": 320,
  "sinopse": "Uma história de mistério e suspense envolvendo um homem que fabrica lágrimas artificiais e os segredos obscuros por trás desse processo.",
  "status": "disponível",
  "altura": 21.00,
  "largura": 14.00,
  "peso": 0.35,
  "profundidade": 2.10,
  "codigoBarras": "9786555656783",
  "autorId": 38,
  "editoraId": 4,
  "fornecedorId": 4,
  "grupoPrecificacaoId": 4,
  "categoriaId": 4,
  "estoqueId": 6
},
{
  "titulo": "Nunca minta",
  "ano": 2020,
  "edicao": "1ª",
  "isbn": "9788595082545",
  "precoCusto": 27.00,
  "precoVenda": 40.90,
  "dataPublicacao": "2020-10-10T00:00:00Z",
  "paginas": 304,
  "sinopse": "Um thriller psicológico que acompanha uma jovem tentando desvendar a verdade por trás das mentiras que ameaçam sua vida e sanidade.",
  "status": "disponível",
  "altura": 20.50,
  "largura": 13.50,
  "peso": 0.34,
  "profundidade": 2.00,
  "codigoBarras": "9788595082545",
  "autorId": 31,
  "editoraId": 2,
  "fornecedorId": 2,
  "grupoPrecificacaoId": 5,
  "categoriaId": 6,
  "estoqueId": 8
}


  ];
  
   
    await prisma.livros.createMany({
      data: livros,
      skipDuplicates: true, // opcional: ignora registros duplicados
    });
      
    console.log('Dados inseridos com sucesso!');
  } catch (error) {
    console.error('Erro ao inserir dados:', error);
  } finally {
    await prisma.$disconnect();
}}
insertLivros();